name = "spark-connector"
title = "MongoDB Spark Connector"
toc_landing_pages = ["/java-api", "/python-api", "/scala-api", "/r-api"]

[constants]
current-version = "2.4.2"
spark-core-version = "2.4.2"
spark-sql-version = "2.4.2"

[substitutions]
ent-build = "MongoDB Enterprise"
hardlink = "http://docs.mongodb.com/docs-spark-connector"